//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_market_data
    {
        public short id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string trade_code { get; set; }
        public Nullable<float> high { get; set; }
        public Nullable<float> low { get; set; }
        public Nullable<float> open { get; set; }
        public Nullable<float> close { get; set; }
        public Nullable<float> volume { get; set; }
    }
}
